sylius_ui:
  events:
    sylius.shop.homepage:
      blocks:
        banner:
          template: "@SyliusShop/Homepage/_banner.html.twig"
          priority: 60
        newsletter:
          template: "@SyliusShop/Homepage/_newsletter.html.twig"
          priority: 30
        latest_products: false
        #        latest_products:
        #          template: "@SyliusShop/Homepage/_latestProducts.html.twig"
        #          priority: -1
        latest_products_carousel: false
        #        latest_products_carousel:
        #          template: "@SyliusShop/Homepage/_latestProductsCarousel.html.twig"
        #          priority: 0
        products_grid: false
        #        products_grid:
        #          template: "@SyliusShop/Homepage/_productsGrid.html.twig"
        #          priority: -1
        about_us: false
        #        about_us:
        #          template: "@SyliusShop/Homepage/_aboutUs.html.twig"
        #          priority: 0
    sylius.shop.product.show.right_sidebar:
      blocks:
        header:
          template: "@SyliusShop/Product/Show/_header.html.twig"
          priority: 50
        after_product_header_legacy:
          template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
          priority: 45
          context:
            event: sylius.shop.product.show.after_product_header
        reviews: false
        #        reviews:
        #          template: "@SyliusShop/Product/Show/_reviews.html.twig"
        #          priority: 40
        after_reviews_legacy:
          template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
          priority: 35
          context:
            event: sylius.shop.product.show.after_reviews
        price_widget:
          template: "@SyliusShop/Product/Show/_priceWidget.html.twig"
          priority: 30
        after_price_legacy:
          template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
          priority: 25
          context:
            event: sylius.shop.product.show.after_price
        short_description:
          template: "@SyliusShop/Product/Show/_shortDescription.html.twig"
          priority: 20
        after_description_legacy:
          template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
          priority: 15
          context:
            event: sylius.shop.product.show.after_description
        variant_selection:
          template: "@SyliusShop/Product/Show/_variantSelection.html.twig"
          priority: 10
        after_add_to_cart_legacy:
          template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
          priority: 5
          context:
            event: sylius.shop.product.show.after_add_to_cart
        cancer_warning:
          template: "bundles/SyliusShopBundle/Product/Show/_cancerWarning.html.twig"
          priority: 0
