sylius_resource:
  resources:
    app.dealer:
      driver: doctrine/orm
      classes:
        model: App\Entity\Dealer
    app.channel_setting:
      driver: doctrine/orm
      classes:
        model: App\Entity\Channel\ChannelSetting
        repository: App\Repository\ChannelSettingRepository
