sylius_shop:
  resource: "@SyliusShopBundle/Resources/config/routing.yml"
  prefix: /{_locale}
  requirements:
    _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$

sylius_shop_payum:
  resource: "@SyliusShopBundle/Resources/config/routing/payum.yml"

sylius_shop_default_locale:
  path: /
  methods: [ GET ]
  defaults:
    _controller: sylius.controller.shop.locale_switch:switchAction

#sylius_shop_product_index:
#  path: /categories/{slug}
#  methods: [ GET ]
#  defaults:
#    _controller: sylius.controller.product:indexAction
#    _sylius:
#      template: "@SyliusShop/Product/index.html.twig"
#      grid: sylius_shop_product
#  requirements:
#    slug: .+
