app_admin_dealer:
  prefix: /admin
  resource: |
    alias: app.dealer
    section: admin
    templates: "@SyliusAdmin\\Crud"
    redirect: update
    grid: app_admin_dealer
    vars:
      all:
        header: 'Dealers'
        subheader: sylius.ui.dealer.title
      index:
        icon: 'file image outline'
  type: sylius.resource

sylius_shop_dealer:
  resource: "routes/dealer.yaml"
  prefix: /dealers

sylius_shop_about:
  resource: "routes/about.yaml"
  prefix: /about-us

bitbag_sylius_cms_plugin:
  resource: "@BitBagSyliusCmsPlugin/Resources/config/routing.yml"

product_search_results:
  path: /search
  methods: [ GET ]
  defaults:
    _controller: sylius.controller.shop.search:searchAction
    _sylius:
      redirect: sylius_shop_homepage
